apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: simple-webapp-docker
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'simple-webapp-docker:latest'
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/kafee651/simple-webapp-flask.git'
    type: Git
  strategy:
    dockerStrategy:
    type: Docker
  triggers:
    - imageChange:
        lastTriggeredImageID: >-
          docker-registry.default.svc:5000/openshift/python@sha256:3403a88a4161c8b8029f4a7d520d4d6e95aeb179f5974b1d2a16b1cfb753cc25
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: 09122dfaf82a0690
      type: Generic
    - github:
        secret: ffc694f180d65be7
      type: GitHub
